spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false